name: Run E2E Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-e2e:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Check out MVD
        run: git clone https://github.com/eclipse-edc/MinimumViableDataspace mvd

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Control Plane Image
        working-directory: mvd
        run: |
          ./gradlew :launchers:controlplane:shadowJar
          docker buildx build -f launchers/controlplane/src/main/docker/Dockerfile --build-arg "JAR=build/libs/controlplane.jar" -t mvd-controlplane launchers/controlplane

      - uses: docker/setup-compose-action@v1
        name: Setup docker compose

      - name: Run Docker Compose
        run: |
          docker compose up --build
          
      - name: Tear down Docker Compose
        if: always()
        run: docker compose down